springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  error:
    include-message: always
    include-stacktrace: on_param
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nttdata?useSSL=false
    username: root
    password: 1237
  application:
    name: UserCRUD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

