server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          default-label: develop
          uri: https://github.com/orion7u7/NTTDATA_Technical_Test
          search-paths: config-data

  application:
    name: ConfigService
